### ISSUE TITLE
Fork doesn't build

### ISSUE THREAD

**Issue by KastenTaco** [raeedcho/temper-zmk-config#2]
Does the firmware still build as is? I can't seem to get it too work.

**Comment by raeedcho** [comment]
I believe it should, but I haven't checked in a while. Looking at your fork, it seems like it didn't build after you changed the `Kconfig.defconfig` file. Have you tried reverting that and checking? It seems like that file is missing a `endif` statement at the end.

**Comment by paradoxicator** [comment]
I'm having the same issue.  I get an exit code 1 and the build fails.  I also tried the Miryoku build using the corne shields and somehow the pinky rows don't work.  However, the main ZMK.dev initial build ones do work (using corne).  I've only tried to flash the left one. 

Anyway, I'm very new to this so it's very quite possible I'm doing a lot of things wrong.  Trying to read the ZMK documentation to learn more.

This is my output:

```
warning: SSD1306_REVERSE_MODE (defined at /__w/temper-zmk-config/temper-zmk-config/config/boards/shields/temper/Kconfig.defconfig:24, /__w/temper-zmk-config/temper-zmk-config/config/boards/shields/temper/Kconfig.defconfig:24) defined without a type

warning: LV_Z_DPI (defined at /__w/temper-zmk-config/temper-zmk-config/config/boards/shields/temper/Kconfig.defconfig:34, /__w/temper-zmk-config/temper-zmk-config/config/boards/shields/temper/Kconfig.defconfig:34) defined without a type

error: Aborting due to Kconfig warnings

Loaded configuration '/__w/temper-zmk-config/temper-zmk-config/zmk/app/boards/arm/nice_nano/nice_nano_v2_defconfig'
Merged configuration '/__w/temper-zmk-config/temper-zmk-config/zmk/app/prj.conf'
Merged configuration '/__w/temper-zmk-config/temper-zmk-config/config/boards/shields/temper/temper_left.conf'
CMake Error at /__w/temper-zmk-config/temper-zmk-config/zephyr/cmake/modules/kconfig.cmake:355 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /__w/temper-zmk-config/temper-zmk-config/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /__w/temper-zmk-config/temper-zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:[66](https://github.com/paradoxicator/temper-zmk-config/actions/runs/8788304045/job/24115461279#step:11:67) (include)
  /__w/temper-zmk-config/temper-zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/tmp/tmp.P6qbItHTpn -GNinja -DBOARD=nice_nano_v2 -DZMK_CONFIG=/__w/temper-zmk-config/temper-zmk-config/config -DSHIELD=temper_left -S/__w/temper-zmk-config/temper-zmk-config/zmk/app
Error: Process completed with exit code 1.

```

**Comment by KastenTaco** [comment]
I'm also fairly novice. Didn't have the time to review the input @raeedcho gave me.

However, I was able to get a build done with this fork right here:
https://github.com/tmcdonell/config-temper-zmk

I did create my own fork off of that and edited it to be a modified miryoku keyboard layout. You can find it here:
https://github.com/KastenTaco/config-temper-zmktest

**Comment by raeedcho** [comment]
Looking into it a bit, it seems there was an update in the ZMK firmware to use Zephyr 3.5 that I didn't keep up with. I'll work on the changes, but feel free to use whatever fork works for you.

**Comment by KastenTaco** [comment]
I just added the missing `endif` statement you brought up earlier and it built just fine! Once again the issue was between keyboard and the chair.

Many thanks! I will be doing the final assembly later today, as my case has almost printed! Very excited. Thanks for all the time you've spent for this great little keyboard 🥇
